version: '3'

tasks:
  default:
    deps:
      - fast-build

  fast-build:
    cmds:
      - go build -o bin/metric-collector .

  clean:
    cmds:
      - rm -rf ./bin/

  rpm:
    dir: rpm/
    cmds:
      - task rpm
